Repository SUSUSSG/PenGreenLiveBackEnd, pull requests merged in 2024-05, with the labels that each got.

#2 [FILE] 테스트 도메인 생성
  build.gradle
  src/main/java/susussg/pengreenlive/test/Controller/TestController.java
  src/main/java/susussg/pengreenlive/test/DTO/TestDTO.java
  src/main/java/susussg/pengreenlive/test/Mapper/TestMapper.java
  src/main/java/susussg/pengreenlive/test/Service/TestService.java
  src/main/java/susussg/pengreenlive/test/Service/TestServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mappers/TestMapper.xml
Labels: 기능추가, 패키지, 테스트

#3 [FEAT] build.gradle 의존성 추가, 실시간 방송 RestController 추가
  build.gradle
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
Labels: 기능추가

#5 [FEAT] 채팅 기본 로직 구현
  .gitignore
  build.gradle
  src/main/java/susussg/pengreenlive/chat/Result.java
  src/main/java/susussg/pengreenlive/chat/config/WebSocketBrokerConfiguration.java
  src/main/java/susussg/pengreenlive/chat/config/WebSocketConfiguration.java
  src/main/java/susussg/pengreenlive/chat/controller/RoomController.java
  src/main/java/susussg/pengreenlive/chat/dto/EnteredRoomDto.java
  src/main/java/susussg/pengreenlive/chat/dto/EnteredRoomResponseDto.java
  src/main/java/susussg/pengreenlive/chat/dto/MessageDto.java
  src/main/java/susussg/pengreenlive/chat/dto/RoomJoinedRequestDto.java
  src/main/java/susussg/pengreenlive/chat/dto/RoomResponseDto.java
  src/main/java/susussg/pengreenlive/chat/entity/EnteredRoom.java
  src/main/java/susussg/pengreenlive/chat/entity/Room.java
  src/main/java/susussg/pengreenlive/chat/entity/RoomStatus.java
  src/main/java/susussg/pengreenlive/chat/entity/User.java
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/chat/handler/MyHandler.java
  src/main/java/susussg/pengreenlive/chat/interceptor/WebsocketBrokerInterceptor.java
  src/main/java/susussg/pengreenlive/chat/repository/WebsocketEnteredRoomRepository.java
  src/main/java/susussg/pengreenlive/chat/repository/WebsocketRoomRepository.java
  src/main/java/susussg/pengreenlive/chat/repository/WebsocketUserRepository.java
  src/main/java/susussg/pengreenlive/chat/service/EnteredRoomService.java
  src/main/java/susussg/pengreenlive/chat/service/RoomService.java
  src/main/java/susussg/pengreenlive/chat/service/UserService.java
  src/main/java/susussg/pengreenlive/chat/service/WebsocketService.java
  src/main/resources/application.yml
Labels: 기능추가, 패키지, 리팩토링

#4 [FEAT] 상품, 방송 카테고리 목록 조회
  build.gradle
  src/main/java/susussg/pengreenlive/dashboard/Controller/CategoryController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/BroadcastCategoryDTO.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/CategoryDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/CategoryMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/CategorySerivceImpl.java
  src/main/java/susussg/pengreenlive/dashboard/Service/CategoryService.java
  src/main/resources/mappers/CategoryMapper.xml
  src/test/java/susussg/pengreenlive/service/CategoryServiceTest.java
Labels: 버그수정, 기능추가

#6 [FEAT] 상점 정보 등록 기능 구현
  src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ShopInfoDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ShopInfoMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoServiceImpl.java
  src/main/resources/mappers/ShopInfoMapper.xml
  src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
Labels: 기능추가

#7 [FIX] 채팅 버그 수정
  build.gradle
  src/main/java/susussg/pengreenlive/chat/README-chatting.md
  src/main/java/susussg/pengreenlive/chat/config/WebSockConfig.java
  src/main/java/susussg/pengreenlive/chat/config/WebSocketBrokerConfiguration.java
  src/main/java/susussg/pengreenlive/chat/config/WebSocketConfiguration.java
  src/main/java/susussg/pengreenlive/chat/controller/ChatController.java
  src/main/java/susussg/pengreenlive/chat/controller/ChatRoomController.java
  src/main/java/susussg/pengreenlive/chat/dto/MessageDto.java
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/chat/handler/MyHandler.java
  src/main/java/susussg/pengreenlive/chat/model/ChatMessage.java
  src/main/java/susussg/pengreenlive/chat/model/ChatRoom.java
  src/main/java/susussg/pengreenlive/chat/repo/ChatRoomRepository.java
Labels: 버그수정, 기능추가, 리팩토링, 스타일

#8 [FIX] 테스트 데이터 삽입 로직 비활성화 처리
  src/main/java/susussg/pengreenlive/chat/config/WebSocketBrokerConfiguration.java
Labels: 스타일

#9 [FILE] : gradle.yml 추가
  .github/workflows/gradle.yml
Labels: 기능추가, 문서

#10 [FEAT] 상점정보 조회 및 수정 기능 구현
  src/main/java/susussg/pengreenlive/config/CorsConfig.java
  src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ShopInfoMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/CategoryServiceImpl.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ShopInfoServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/main/resources/mappers/ShopInfoMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
  src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
Labels: 버그수정, 기능추가, 리팩토링

#11 [FEAT] 한줄공지 메소드 추가
  src/main/java/susussg/pengreenlive/chat/controller/ChatController.java
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
Labels: 기능추가

#12 [FEAT] 상품 목록 조회 구현
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
Labels: 기능추가

#13 [FEAT] 금칙어 필터링 백엔드 서비스
  build.gradle
  src/main/java/susussg/pengreenlive/config/SchedulerConfig.java
  src/main/java/susussg/pengreenlive/util/DTO/BanwordDTO.java
  src/main/java/susussg/pengreenlive/util/DTO/BanwordValidationResultDTO.java
  src/main/java/susussg/pengreenlive/util/DTO/ForbiddenWordDTO.java
  src/main/java/susussg/pengreenlive/util/Mapper/ForbiddenWordMapper.java
  src/main/java/susussg/pengreenlive/util/Service/BanwordService.java
  src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordService.java
  src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordServiceImpl.java
  src/main/resources/mappers/ForbiddenWordMapper.xml
  src/test/java/susussg/pengreenlive/service/BanwordServiceTest.java
  src/test/java/susussg/pengreenlive/service/ForbiddenWordTest.java
Labels: 기능추가, 패키지, 리팩토링, 테스트

#14 [FIX] CORS 충돌 수정
  src/main/java/susussg/pengreenlive/config/CorsConfig.java
Labels: 버그수정, 리팩토링

#15 [FEAT] 비속어 필터링 채팅 연결
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/chat/handler/MyHandler.java
Labels: 기능추가

#16 [FEAT] 세션 정보로 채팅 닉네임 설정
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/chat/handler/MyHandler.java
  src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java
  src/main/java/susussg/pengreenlive/user/Service/UserService.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/resources/mappers/UserMapper.xml
  src/test/java/susussg/pengreenlive/service/UserServiceTest.java
Labels: 기능추가, CSS, 리팩토링

#17 [FIX] 입,퇴장 메시지 비활성화 수정
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
Labels: 버그수정

#18 [FEAT] 메인 화면 백엔드 API
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/main/DTO/LiveChanceCarouselDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/MainCarouselDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/MainCarouselProductDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/ScheduledBroadcastDTO.java
  src/main/java/susussg/pengreenlive/main/Mapper/MainMapper.java
  src/main/java/susussg/pengreenlive/main/Service/MainService.java
  src/main/java/susussg/pengreenlive/main/Service/MainServiceImpl.java
  src/main/resources/mappers/MainMapper.xml
  src/test/java/susussg/pengreenlive/service/MainServiceTest.java
Labels: 기능추가, 패키지, 테스트

#19 [FEAT] 상품 등록 기능 구현
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 기능추가

#20 [REFACTOR] 각 판매자별 상품 목록 조회로 수정
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 기능추가, 리팩토링

#21 [FEAT] 상품 주문 API 및 결제 승인 API 구현
  build.gradle
  src/main/java/susussg/pengreenlive/config/ModelConfig.java
  src/main/java/susussg/pengreenlive/order/OrderController.java
  src/main/java/susussg/pengreenlive/order/OrderRepository.java
  src/main/java/susussg/pengreenlive/order/domain/Order.java
  src/main/java/susussg/pengreenlive/order/dto/OrderFormDTO.java
  src/main/java/susussg/pengreenlive/order/service/OrderService.java
  src/main/java/susussg/pengreenlive/payment/PaymentController.java
  src/main/java/susussg/pengreenlive/payment/dto/verifyPaymentDTO.java
  src/main/java/susussg/pengreenlive/payment/service/PaymentService.java
Labels: 기능추가

#22 [FEAT] 현재 시청자수 확인 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
Labels: 기능추가

#23 [FEAT] 라이브 등록 API
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveRegisterController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BenefitDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastCategoryDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastProductDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/ChannelSalesProductDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/FaqDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/NoticeDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveRegisterMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterServiceImpl.java
  src/main/resources/mappers/LiveRegisterMapper.xml
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
Labels: 기능추가

#24 [REFACTOR] 상품 이미지 및 등록 기능 수정
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 리팩토링

#26 [FEAT] : 방송 통계 생성, 방송 통계 조회, 좋아요 증감, 평균 시청자수 최대 시청자수 업데이트 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
  src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java
  src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
Labels: 기능추가, 테스트

#27 [FEAT] 상품 정보 수정 기능 구현
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 기능추가, 테스트

#29 [FEAT] 채널 판매 상품 삭제 기능 구현
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 기능추가

#25 [FEAT] 구독, 일정표 페이지
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/main/DTO/ScheduledBroadcastDTO.java
  src/main/java/susussg/pengreenlive/main/Mapper/MainMapper.java
  src/main/java/susussg/pengreenlive/main/Service/MainService.java
  src/main/java/susussg/pengreenlive/main/Service/MainServiceImpl.java
  src/main/resources/mappers/MainMapper.xml
Labels: 기능추가

#30 [FEAT] 메인화면, 일정표 페이지 스켈레톤 UI 추가 및 메소드 시간 측정 AOP
  build.gradle
  src/main/java/susussg/pengreenlive/config/aop/TimeTrace.java
  src/main/java/susussg/pengreenlive/config/aop/TimeTraceAspect.java
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
Labels: 기능추가

#31 [FEAT] 레디스 세팅
  build.gradle
  src/main/java/susussg/pengreenlive/config/RedisConfig.java
  src/main/java/susussg/pengreenlive/payment/PaymentController.java
  src/main/java/susussg/pengreenlive/payment/dto/verifyPaymentDTO.java
Labels: 기능추가

#32 [FEAT] : 평균 시청자, 최고 시청자, 방송 진행 시간 업데이트 기능 추가, 방송 통계 객체에 조회수 필드 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
  src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java
  src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
Labels: 기능추가

#33 [FEAT] 방송 생성 시 방송 통계 함께 생성되게 추가
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterServiceImpl.java
Labels: 기능추가

#34 [CHORE] 깃허브 워크플로우 yml 파일 레디스 설정 추가
  .github/workflows/gradle.yml
Labels: 기능추가, 문서

#35 [FEAT] 방송 예정 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveRegisterController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/UpcomingBroadcastInfoDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveRegisterMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterServiceImpl.java
  src/main/resources/mappers/LiveRegisterMapper.xml
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
Labels: 버그수정, 기능추가, 리팩토링, 테스트

#36 [FEAT] 슬라이드 수정 및 이미지 리사이징 및 S3 연동
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/susussg/pengreenlive/config/S3Config.java
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/util/Controller/S3Controller.java
  src/main/java/susussg/pengreenlive/util/Service/ImageService.java
  src/main/java/susussg/pengreenlive/util/Service/S3Service.java
  src/main/resources/mappers/MainMapper.xml
Labels: 기능추가, 리팩토링

#38 [FEAT] 메인화면 이미지 조회 로직 변경
  src/main/java/susussg/pengreenlive/main/DTO/LiveChanceCarouselDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/MainCarouselDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/MainCarouselProductDTO.java
  src/main/java/susussg/pengreenlive/main/DTO/ScheduledBroadcastDTO.java
  src/main/resources/mappers/MainMapper.xml
  src/test/java/susussg/pengreenlive/service/MainServiceTest.java
Labels: 리팩토링

#39 [REFACTOR] 상품 등록, 수정 이미지 업로드 로직 변경
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/java/susussg/pengreenlive/util/Service/ByteArrayMultipartFile.java
  src/main/resources/mappers/ProductMapper.xml
Labels: 리팩토링

#40 [FEAT] S3이미지 업로드 시 이름 충돌 방지 코드 추가
  src/main/java/susussg/pengreenlive/util/Service/S3Service.java
  src/main/resources/mappers/MainMapper.xml
Labels: 기능추가, 리팩토링

#41 [FEAT]: 누적 시청자 수 집계 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
  src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java
  src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
Labels: 기능추가

#42 [FIX] UUID 및 라이브 조회 오류 수정
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/main/DTO/LiveChanceCarouselDTO.java
  src/main/resources/mappers/MainMapper.xml
Labels: 버그수정, 리팩토링

#43 [REFACTOR] 방송 등록하기 이미지 로직 변경
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastRegisterController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveRegisterController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastRegisterMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastRegisterService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastRegisterServiceImpl.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveRegisterServiceImpl.java
  src/main/resources/mappers/BroadcastRegisterMapper.xml
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
Labels: 버그수정, 리팩토링, 문서

#44 [FEAT] 상품 통계 API 작성
  src/main/java/susussg/pengreenlive/statistics/controller/ProductStatisticsController.java
  src/main/java/susussg/pengreenlive/statistics/dto/LabelInfo.java
  src/main/java/susussg/pengreenlive/statistics/dto/ProductDetailsDTO.java
  src/main/java/susussg/pengreenlive/statistics/dto/ProductInChannelDTO.java
  src/main/java/susussg/pengreenlive/statistics/dto/SalesDataDTO.java
  src/main/java/susussg/pengreenlive/statistics/mapper/ProductStatisticsMapper.java
  src/main/java/susussg/pengreenlive/statistics/service/ProductStatisticsService.java
  src/main/java/susussg/pengreenlive/statistics/service/ProductStatisticsServiceImpl.java
  src/main/resources/mappers/ProductStatisticsMapper.xml
Labels: 기능추가

#46 [FEAT] 브랜드페이 api
  src/main/java/susussg/pengreenlive/config/RedisConfig.java
  src/main/java/susussg/pengreenlive/payment/BrandPayController.java
  src/main/java/susussg/pengreenlive/payment/PaymentController.java
Labels: 기능추가

#47 [FEAT] 리뷰 확인 및 삭제 기능 구현
  src/main/java/susussg/pengreenlive/order/controller/ReviewController.java
  src/main/java/susussg/pengreenlive/order/dto/ReviewDTO.java
  src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java
  src/main/java/susussg/pengreenlive/order/service/ReviewService.java
  src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java
  src/main/resources/mappers/ReviewMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
  src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
  src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
Labels: 기능추가, 리팩토링, 테스트

#48 [FEAT] GPT 기본 구조 구현
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openai/dto/ChatRequestDTO.java
  src/main/java/susussg/pengreenlive/openai/dto/ChatResponseDTO.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
Labels: 기능추가, 문서

#49 [FEAT] : 방송 통계 API 추가 및 파일명 변경
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastRegisterController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/OpenViduController.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/resources/mappers/BroadcastMapper.xml
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
  src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java
  src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
  src/test/java/susussg/pengreenlive/service/ShopInfoServiceTest.java
Labels: 기능추가, 리팩토링, 스타일, 테스트

#50 [FEAT] 챗봇 기능 추가 및 리팩토링
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
Labels: 기능추가, 리팩토링

#51 [FEAT] 라이브 방송 기본 정보 API
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LiveBroadcastInfoDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java
  src/main/resources/mappers/BroadcastMapper.xml
  src/main/resources/mappers/LiveBroadcastMapper.xml
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
  src/test/java/susussg/pengreenlive/service/LiveBroadcastInfoTest.java
Labels: 기능추가, 스타일, 테스트

#52 [REFACTOR] 리뷰 등록 기능 수정
  src/main/java/susussg/pengreenlive/order/controller/ReviewController.java
  src/main/java/susussg/pengreenlive/order/dto/ReviewDTO.java
  src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java
  src/main/java/susussg/pengreenlive/order/service/ReviewService.java
  src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java
  src/main/resources/mappers/ReviewMapper.xml
  src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
Labels: 버그수정, 리팩토링

#54 [FEAT] OpenAI 챗봇
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openai/dto/RecentOrderDTO.java
  src/main/java/susussg/pengreenlive/openai/mapper/OpenAIMapper.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIQueryService.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIQueryServiceImpl.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
  src/main/resources/mappers/ChatbotMapper.xml
Labels: 기능추가, CSS

#53 [FEAT] 평균시청시간 집계 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/WatchTimeController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/WatchTime.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/WatchTimeMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeService.java
  src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeServiceImpl.java
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
  src/main/resources/mappers/WatchTimeMapper.xml
Labels: 기능추가

#55 [FEAT] 최근 본 방송 목록 조회
  src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java
  src/main/java/susussg/pengreenlive/mypage/DTO/HistoryDTO.java
  src/main/java/susussg/pengreenlive/mypage/Mapper/HistoryMapper.java
  src/main/java/susussg/pengreenlive/mypage/Service/HistoryService.java
  src/main/java/susussg/pengreenlive/mypage/Service/HistoryServiceImpl.java
  src/main/resources/mappers/HistoryMapper.xml
  src/test/java/susussg/pengreenlive/service/HistoryServiceTest.java
Labels: 기능추가, 리팩토링

#56 [FEAT] 시청기록 쿼리 및 DTO 수정
  src/main/java/susussg/pengreenlive/mypage/DTO/HistoryDTO.java
  src/main/resources/mappers/HistoryMapper.xml
Labels: 기능추가, 리팩토링

#58 [FEAT] 주문 관련 JPA 설정 및 API 구현
  src/main/java/susussg/pengreenlive/order/controller/OrderController.java
  src/main/java/susussg/pengreenlive/order/domain/Broadcast.java
  src/main/java/susussg/pengreenlive/order/domain/Channel.java
  src/main/java/susussg/pengreenlive/order/domain/Order.java
  src/main/java/susussg/pengreenlive/order/domain/Product.java
  src/main/java/susussg/pengreenlive/order/domain/ProductStock.java
  src/main/java/susussg/pengreenlive/order/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/order/dto/OrderFormDTO.java
  src/main/java/susussg/pengreenlive/order/dto/ProductStockDTO.java
  src/main/java/susussg/pengreenlive/order/repository/OrderRepository.java
  src/main/java/susussg/pengreenlive/order/repository/ProductRepository.java
  src/main/java/susussg/pengreenlive/order/repository/ProductStockRepository.java
  src/main/java/susussg/pengreenlive/order/service/OrderService.java
  src/main/java/susussg/pengreenlive/order/util/UUIDConverter.java
  src/main/resources/application.properties
  src/test/java/susussg/pengreenlive/order/service/OrderServiceTest.java
Labels: 기능추가, 테스트

#59 [FEAT] 시간대 별 시청자 수 집계 및 조회 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastViewerCount.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastViewerCountMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastViewerCountService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastViewerCountServiceImpl.java
  src/main/java/susussg/pengreenlive/broadcast/service/WatchTimeServiceImpl.java
  src/main/resources/mappers/BroadcastViewerCountMapper.xml
Labels: 기능추가

#60 [FEAT] 라이브 보드 방송 판매 상품 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LiveBroadcastProductDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java
  src/main/resources/mappers/LiveBroadcastMapper.xml
  src/test/java/susussg/pengreenlive/mapper/LiveBroadcastProductMapperTest.java
  src/test/java/susussg/pengreenlive/mapper/LiveRegisterMapperTest.java
  src/test/java/susussg/pengreenlive/service/LiveBroadcastProductTest.java
Labels: 기능추가, 테스트

#61 [FEAT] 상품 리뷰 유해성 검사
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
Labels: 기능추가

#62 [FEAT] 리뷰 내용 문자열 출력
  src/main/java/susussg/pengreenlive/naver/mapper/ReviewSummaryMapper.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryService.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java
  src/main/resources/mappers/ReviewSummaryMapper.xml
  src/test/java/susussg/pengreenlive/service/ReviewSummaryServiceTest.java
Labels: 기능추가

#63 [FEAT] 의미 연결망 생성 로직
  build.gradle
  src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java
  src/main/java/susussg/pengreenlive/statistics/py/SCDream5.otf
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
  src/main/java/susussg/pengreenlive/statistics/service/PythonService.java
  src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
  src/main/resources/application.properties
Labels: 기능추가

#64 [REFACTOR] TB_PRODUCT_CLICKS 테이블 삭제에 따른 코드 변경
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastProductDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastStatistics.java
  src/main/java/susussg/pengreenlive/broadcast/dto/ProductClick.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/ProductClicksMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductClickService.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductClickServiceImpl.java
  src/main/resources/mappers/ProductClicksMapper.xml
Labels: 리팩토링, 스타일

#65 [FEAT] 상품 시퀀스로 리뷰 의미망 분석
  src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
  src/main/java/susussg/pengreenlive/statistics/service/PythonService.java
  src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
Labels: 기능추가, 패키지, 문서

#67 [FEAT] 구매 전환률 관련 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LiveBroadcastProductDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/ProductClicksMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductClickService.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductClickServiceImpl.java
  src/main/resources/mappers/LiveBroadcastMapper.xml
  src/main/resources/mappers/ProductClicksMapper.xml
Labels: 기능추가, 리팩토링

#68 [FEAT] 분석 시 데이터 부족 예외 처리
  .github/workflows/gradle.yml
  src/main/java/susussg/pengreenlive/statistics/dto/ProductDetailsDTO.java
  src/main/java/susussg/pengreenlive/statistics/dto/ProductInChannelDTO.java
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
  src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
  src/main/resources/mappers/ProductStatisticsMapper.xml
Labels: 리팩토링

#69 [FIX] 메소드명 오류 수정
  src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
Labels: 버그수정

#70 [FEAT] 일반회원가입 api
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/order/domain/Order.java
  src/main/java/susussg/pengreenlive/order/util/UUIDConverter.java
  src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java
  src/main/java/susussg/pengreenlive/user/Service/UserService.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/java/susussg/pengreenlive/user/controller/AccountController.java
  src/main/java/susussg/pengreenlive/user/domain/LocalLogin.java
  src/main/java/susussg/pengreenlive/user/domain/SocialLogin.java
  src/main/java/susussg/pengreenlive/user/domain/TbUser.java
  src/main/java/susussg/pengreenlive/user/dto/SignupFormDTO.java
  src/main/java/susussg/pengreenlive/user/repository/UserRepository.java
  src/main/java/susussg/pengreenlive/user/service/AccountService.java
  src/main/resources/mappers/UserMapper.xml
  src/test/java/susussg/pengreenlive/service/UserServiceTest.java
  src/test/java/susussg/pengreenlive/user/service/AccountServiceTest.java
Labels: 기능추가, 테스트

#71 [FIX] 파이썬 로그 자바 콘솔에 표시
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
  src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
Labels: 버그수정, 리팩토링, 테스트

#73 [FEAT] 상품별 리뷰 리스트 조회
  src/main/java/susussg/pengreenlive/naver/controller/ReviewSummaryController.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryService.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java
Labels: 기능추가

#72 [FIX] 로그 출력 수정
  src/main/java/susussg/pengreenlive/statistics/py/word_network.py
  src/main/java/susussg/pengreenlive/statistics/service/PythonServiceImpl.java
Labels: 버그수정

#74 [FEAT] 공지, 자주묻는 질문 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java
  src/main/resources/mappers/LiveBroadcastMapper.xml
Labels: 버그수정, 기능추가, 스타일

#75 [FEAT] 시청화면 방송판매상품 API 추가 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LiveBroadcastProductDTO.java
  src/main/resources/mappers/LiveBroadcastMapper.xml
Labels: 기능추가, 리팩토링

#76 [FEAT] 휴대폰 번호 인증 api
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/susussg/pengreenlive/config/RedisConfig.java
  src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java
  src/main/java/susussg/pengreenlive/payment/controller/PaymentController.java
  src/main/java/susussg/pengreenlive/user/controller/AccountController.java
  src/main/java/susussg/pengreenlive/user/service/AccountService.java
  src/main/java/susussg/pengreenlive/user/util/SmsUtil.java
  src/test/java/susussg/pengreenlive/user/service/AccountServiceTest.java
Labels: 기능추가

#77 [FEAT] 리뷰 내용 감정 분석
  src/main/java/susussg/pengreenlive/naver/controller/SentimentReviewController.java
  src/main/java/susussg/pengreenlive/naver/dto/SentimentRequestDTO.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java
  src/main/java/susussg/pengreenlive/naver/service/SentimentService.java
  src/main/java/susussg/pengreenlive/naver/service/SentimentServiceImpl.java
Labels: 기능추가

#79 [FEAT] 리뷰 감정 분석 및 프롬프트 AI 도입
  src/main/java/susussg/pengreenlive/naver/controller/SentimentReviewController.java
  src/main/java/susussg/pengreenlive/naver/mapper/ReviewSummaryMapper.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryService.java
  src/main/java/susussg/pengreenlive/naver/service/ReviewSummaryServiceImpl.java
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openai/dto/AiBroadcastPromptDTO.java
  src/main/java/susussg/pengreenlive/openai/mapper/OpenAIMapper.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIQueryService.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIQueryServiceImpl.java
  src/main/java/susussg/pengreenlive/openai/service/OpenAIService.java
  src/main/resources/mappers/ChatbotMapper.xml
  src/main/resources/mappers/ReviewSummaryMapper.xml
Labels: 기능추가

#80 [FEAT] 방송 시작, 종료 시간 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastTimeDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java
  src/main/resources/mappers/BroadcastMapper.xml
  src/test/java/susussg/pengreenlive/mapper/BroadcastMapperTest.java
Labels: 기능추가, 테스트

#81 [FEAT] 구매페이지 내 리뷰 조회
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductReviewController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/ProductReviewDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/ProductReviewMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductReviewService.java
  src/main/java/susussg/pengreenlive/broadcast/service/ProductReviewServiceImpl.java
  src/main/resources/mappers/ProductReviewMapper.xml
Labels: 버그수정, 기능추가

#82 [FEAT] 유저 구독 목록 조회
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/main/DTO/SubscribedChannelDTO.java
  src/main/java/susussg/pengreenlive/main/Mapper/MainMapper.java
  src/main/java/susussg/pengreenlive/main/Service/MainService.java
  src/main/java/susussg/pengreenlive/main/Service/MainServiceImpl.java
  src/main/resources/mappers/MainMapper.xml
Labels: 기능추가

#84 [FEAT] 녹색제품정보 OPEN API
  src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java
  src/main/java/susussg/pengreenlive/openapi/service/GreenProductService.java
Labels: 기능추가

#83 [FEAT] 로그인 구현 및 오류 수정
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/susussg/pengreenlive/config/SecurityConfig.java
  src/main/java/susussg/pengreenlive/login/dto/Member.java
  src/main/java/susussg/pengreenlive/login/dto/UserDTO.java
  src/main/java/susussg/pengreenlive/login/dto/VendorDTO.java
  src/main/java/susussg/pengreenlive/login/role/MemberRole.java
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/java/susussg/pengreenlive/login/service/SecurityService.java
  src/main/java/susussg/pengreenlive/order/util/UUIDConverter.java
  src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java
  src/main/java/susussg/pengreenlive/user/service/AccountService.java
  src/main/java/susussg/pengreenlive/vendor/mapper/VendorMapper.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/VendorMapper.xml
  src/test/java/susussg/pengreenlive/login/service/SecurityServiceTest.java
  src/test/java/susussg/pengreenlive/user/service/AccountServiceTest.java
Labels: 버그수정, 기능추가, 스타일

#85 [FEAT] 실시간 방송 상품 상태 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LiveProductStatsDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/LiveBroadcastMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastService.java
  src/main/java/susussg/pengreenlive/broadcast/service/LiveBroadcastServiceImpl.java
  src/main/resources/mappers/LiveBroadcastMapper.xml
Labels: 기능추가

#87 [TEST] 시큐리티 20% 적용 테스트
  src/main/java/susussg/pengreenlive/config/SecurityConfig.java
  src/main/java/susussg/pengreenlive/login/dto/Member.java
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/java/susussg/pengreenlive/login/service/SecurityService.java
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/order/controller/OrderController.java
  src/main/java/susussg/pengreenlive/order/controller/ReviewController.java
  src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java
  src/main/java/susussg/pengreenlive/order/service/ReviewService.java
  src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java
  src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java
  src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java
  src/main/java/susussg/pengreenlive/user/Service/UserService.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/java/susussg/pengreenlive/user/controller/UserController.java
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
Labels: 테스트

#88 [REFACTOR] API 엔드포인트 변경
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductReviewController.java
  src/main/java/susussg/pengreenlive/dashboard/Controller/CategoryController.java
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/Controller/ShopInfoController.java
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java
  src/main/java/susussg/pengreenlive/naver/controller/ReviewSummaryController.java
  src/main/java/susussg/pengreenlive/naver/controller/SentimentReviewController.java
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java
  src/main/java/susussg/pengreenlive/order/controller/ReviewController.java
  src/main/java/susussg/pengreenlive/statistics/controller/ProductStatisticsController.java
  src/main/java/susussg/pengreenlive/test/Controller/TestController.java
Labels: 리팩토링

#89 [FEAT] 추가 금칙어 등록 API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/util/Mapper/ForbiddenWordMapper.java
  src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordService.java
  src/main/java/susussg/pengreenlive/util/Service/ForbiddenWordServiceImpl.java
  src/main/resources/mappers/ChatbotMapper.xml
  src/main/resources/mappers/ForbiddenWordMapper.xml
  src/main/resources/mappers/MainMapper.xml
Labels: 기능추가

#90 [FEAT] 실시간 자막 웹소켓 통신 기능 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/Subtitle.java
  src/main/java/susussg/pengreenlive/chat/config/WebSockConfig.java
Labels: 기능추가, 리팩토링

#93 [FEAT] 환경 인증 상품 등록 및 목록 조회
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/GreenLabelDTO.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ProductDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/java/susussg/pengreenlive/util/Service/DateUtil.java
  src/main/resources/mappers/ProductMapper.xml
Labels: 버그수정, 기능추가

#91 [FEAT] 금칙어 추가 로직
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/java/susussg/pengreenlive/util/Service/BanwordService.java
Labels: 기능추가

#92 [FEAT] 실시간 방송 종료 SSE API 구현
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/resources/mappers/BroadcastMapper.xml
Labels: 기능추가, 스타일

#94 [FEAT] 방송 시청 기록 저장 API 구현
  src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java
  src/main/java/susussg/pengreenlive/mypage/Mapper/HistoryMapper.java
  src/main/java/susussg/pengreenlive/mypage/Service/HistoryService.java
  src/main/java/susussg/pengreenlive/mypage/Service/HistoryServiceImpl.java
  src/main/resources/mappers/HistoryMapper.xml
Labels: 기능추가

#95 [FIX] 평균 구매 개수 쿼리문 수정
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
Labels: 버그수정

#96 [FEAT] Cors 오류 수정 및 uuid 바인딩
  .github/workflows/gradle.yml
  src/main/java/susussg/pengreenlive/broadcast/controller/OpenViduController.java
  src/main/java/susussg/pengreenlive/config/CorsConfig.java
  src/main/java/susussg/pengreenlive/config/RedisConfig.java
  src/main/java/susussg/pengreenlive/config/SecurityConfig.java
  src/main/java/susussg/pengreenlive/login/dto/Member.java
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/java/susussg/pengreenlive/login/service/CustomOncePerRequestFilter.java
  src/main/java/susussg/pengreenlive/login/service/CustomUsernamePasswordAuthenticationTokenDeserializer.java
  src/main/java/susussg/pengreenlive/login/service/SecurityService.java
  src/main/java/susussg/pengreenlive/mypage/Controller/HistoryController.java
  src/main/java/susussg/pengreenlive/order/controller/ReviewController.java
  src/main/java/susussg/pengreenlive/order/mapper/ReviewMapper.java
  src/main/java/susussg/pengreenlive/order/service/ReviewService.java
  src/main/java/susussg/pengreenlive/order/service/ReviewServiceImpl.java
  src/main/java/susussg/pengreenlive/user/Mapper/UserMapper.java
  src/main/java/susussg/pengreenlive/user/Service/UserService.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/java/susussg/pengreenlive/user/controller/UserController.java
  src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java
  src/main/resources/application.properties
  src/main/resources/mappers/ReviewMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/test/java/susussg/pengreenlive/service/ReviewServiceTest.java
Labels: 버그수정, 기능추가, 리팩토링

#97 [FIX] 상품 정보 수정 상품 이미지 null값 오류 수정
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/dashboard/DTO/ProductUpdateDTO.java
  src/main/java/susussg/pengreenlive/dashboard/Mapper/ProductMapper.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductService.java
  src/main/java/susussg/pengreenlive/dashboard/Service/ProductServiceImpl.java
  src/main/resources/mappers/ProductMapper.xml
  src/test/java/susussg/pengreenlive/service/ProductServiceTest.java
Labels: 버그수정

#98 [FIX] Security cors 오류 수정
  src/main/java/susussg/pengreenlive/config/SecurityConfig.java
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/java/susussg/pengreenlive/user/controller/UserController.java
  src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java
  src/main/resources/mappers/UserMapper.xml
Labels: 버그수정

#99 [feat] 프론트 url 수정
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/resources/application.properties
Labels: 기능추가

#101 [FIX] 채팅 및 프롬프트 버그 수정
  src/main/java/susussg/pengreenlive/chat/handler/BrokerController.java
  src/main/resources/mappers/MainMapper.xml
Labels: 버그수정, CSS, 리팩토링

#102 [REFACTOR] 좋아요 중복 방지 추가 및 좋아요 정보 저장 테이블 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/LikeDTO.java
  src/main/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapper.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsService.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceImpl.java
  src/main/resources/mappers/BroadcastStatisticsMapper.xml
Labels: 버그수정, 기능추가, 리팩토링

#103 [FIX] 방송 DTO 데이터 타입 수정
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/ChannelSalesProductDTO.java
Labels: 버그수정

#104 [FEAT] Swagger UI 추가
  build.gradle
  src/main/java/susussg/pengreenlive/dashboard/Controller/ProductController.java
  src/main/java/susussg/pengreenlive/util/Controller/SwaggerConfig.java
  src/main/resources/application.properties
Labels: 기능추가

#105 [FEAT] 사업자 등록 인증 구현
  .github/workflows/gradle.yml
  src/main/java/susussg/pengreenlive/vendor/controller/VendorAccountController.java
  src/main/java/susussg/pengreenlive/vendor/service/VendorAccountService.java
Labels: 기능추가

#106 [REFACTOR] 라이브 준비 전체 상품 보여주기 수정
  src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java
  src/main/resources/mappers/BroadcastMapper.xml
Labels: 리팩토링

#109 [FIX] 방송 에정 날짜 타입 변경
  src/main/java/susussg/pengreenlive/broadcast/dto/PrepareBroadcastInfoDTO.java
Labels: 버그수정

#108 [test] 문자 발송 오류 로그
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastDTO.java
  src/main/java/susussg/pengreenlive/broadcast/dto/BroadcastRegistrationRequestDTO.java
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java
  src/main/java/susussg/pengreenlive/config/SwaggerConfig.java
  src/main/java/susussg/pengreenlive/login/service/CustomAuthenticationFilter.java
  src/main/java/susussg/pengreenlive/order/domain/Broadcast.java
  src/main/java/susussg/pengreenlive/order/domain/Order.java
  src/main/java/susussg/pengreenlive/order/domain/Product.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/java/susussg/pengreenlive/user/controller/AccountController.java
  src/main/java/susussg/pengreenlive/user/controller/UserController.java
  src/main/java/susussg/pengreenlive/user/dto/UpdateUserFormDTO.java
  src/main/java/susussg/pengreenlive/user/util/SmsUtil.java
  src/main/resources/mappers/BroadcastMapper.xml
  src/main/resources/mappers/UserMapper.xml
  src/test/java/susussg/pengreenlive/broadcast/mapper/BroadcastStatisticsMapperTest.java
  src/test/java/susussg/pengreenlive/broadcast/service/BroadcastStatisticsServiceTest.java
Labels: 테스트

#110 [FIX] 주문 오류, 방송 등록 오류 수정
  src/main/java/susussg/pengreenlive/broadcast/service/BroadcastServiceImpl.java
  src/main/java/susussg/pengreenlive/order/controller/OrderController.java
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
Labels: 버그수정

#111 [FEAT] S3 설정 추가
  src/main/java/susussg/pengreenlive/util/Service/S3Service.java
  src/main/resources/mappers/MainMapper.xml
Labels: 버그수정, 기능추가

#112 [FEAT] 자막 번역 기능 추가
  .github/workflows/gradle.yml
  src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java
  src/main/java/susussg/pengreenlive/broadcast/dto/Subtitle.java
  src/main/java/susussg/pengreenlive/broadcast/service/TranslationService.java
  src/main/java/susussg/pengreenlive/broadcast/service/TranslationServiceImpl.java
  src/test/java/susussg/pengreenlive/broadcast/service/TranslationServiceImplTest.java
Labels: 기능추가

#113 [STYLE] Swagger API 설명 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastStatisticsController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/BroadcastViewerCountController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/OpenViduController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/ProductClickController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/SubtitleController.java
  src/main/java/susussg/pengreenlive/broadcast/controller/WatchTimeController.java
  src/main/java/susussg/pengreenlive/chat/config/WebSockConfig.java
Labels: 스타일

#115 [STYLE] Swagger API 설명 추가
  src/main/java/susussg/pengreenlive/broadcast/controller/LiveBroadcastController.java
Labels: 문서

#117 [FEAT] 스웨거 등록
  src/main/java/susussg/pengreenlive/main/Controller/MainController.java
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/order/controller/OrderController.java
  src/main/java/susussg/pengreenlive/payment/controller/BrandPayController.java
  src/main/java/susussg/pengreenlive/payment/controller/PaymentController.java
  src/main/java/susussg/pengreenlive/user/controller/AccountController.java
  src/main/java/susussg/pengreenlive/user/controller/UserController.java
  src/main/java/susussg/pengreenlive/vendor/controller/VendorAccountController.java
Labels: 기능추가

#116 [STYLE] Swagger 어노테이션 설명 추가
  src/main/java/susussg/pengreenlive/chat/controller/ChatController.java
  src/main/java/susussg/pengreenlive/chat/controller/ChatRoomController.java
  src/main/java/susussg/pengreenlive/chat/controller/RoomController.java
  src/main/java/susussg/pengreenlive/openai/controller/OpenAIController.java
  src/main/java/susussg/pengreenlive/openapi/controller/GreenProductController.java
  src/main/java/susussg/pengreenlive/statistics/controller/PythonController.java
  src/main/java/susussg/pengreenlive/util/Controller/S3Controller.java
Labels: 스타일

#118 [FEAT] 프로필 이미지 압축률 수정
  src/main/java/susussg/pengreenlive/user/Service/UserServiceImpl.java
  src/main/resources/mappers/VendorMapper.xml
Labels: 버그수정
